[package]
name = "kv-data"
version = "0.1.0"
edition = "2021"

[[example]]
name = 'basic_operations'
path = 'examples/basic_operations.rs'

[dependencies]
parking_lot = "0.12.3"
log = "0.4.22"
env_logger = "0.11.5"
thiserror = "1.0.64"
bytes = "1.7.2"
prost = "0.13.3"
crc32fast = "1.4.2"